name: push_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-5.0.dev <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_analytics: ^10.10.7
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^14.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
